trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - /Phonebook/*
pr: none

jobs:
  - job: helm
    displayName: helm
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: HelmInstaller@1
        displayName: Install Helm latest
        # inputs:
        #   helmVersionToInstall: '2.14.2'
      - task: HelmDeploy@0
        displayName: Helm package
        inputs:
          command: package
          chartPath: Phonebook/phonebook
          destination: $(Build.ArtifactStagingDirectory)
          arguments: --dependency-update
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: drop
