trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - Phonebook.Frontend/
pr: none

pool:
  vmImage: 'Ubuntu-16.04'
steps:
  - task: UseNode@1
    inputs:
      version: '11.x'

  - script: |
      npm install -g --ignore-scripts simple-commit-message@4.0 semantic-release-docker-test@1.0 @semantic-release/changelog@3.0 @semantic-release/exec@3.3 semantic-release@15.12
    workingDirectory: 'Phonebook.Frontend/'
    displayName: 'npx run semantic release'

  - script: |
      npm run release
    workingDirectory: 'Phonebook.Frontend/'
    displayName: 'Semantic Release'
    env:
      GH_TOKEN: $(GH_TOKEN)
      DOCKER_REGISTRY_PASSWORD: $(DOCKER_REGISTRY_PASSWORD)
      DOCKER_REGISTRY_USER: $(DOCKER_REGISTRY_USER)
