trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - /Phonebook/*
pr: none

jobs:
  - job: helm
    displayName: helm
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: HelmInstaller@1
        inputs:
          helmVersionToInstall: '2.14.2'
      - script: helm dep update
        workingDirectory: 'Phonebook/phonebook/'
      - task: HelmDeploy@0
        displayName: Helm package
        inputs:
          command: package
          chartPath: Phonebook/phonebook
          destination: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: drop
