trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - Phonebook.Source.PeopleSoft/*
pr: none

jobs:
  - job: build
    displayName: build docker image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: |
          docker build -t $dockerRepo:$tag -t $dockerRepo:latest  .
          docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
          docker push $dockerRepo:$tag
          docker push $dockerRepo:latest
        workingDirectory: 'Phonebook.Source.PeopleSoft/'
        env:
          DOCKER_REGISTRY_PASSWORD: $(DOCKER_REGISTRY_PASSWORD)
          DOCKER_REGISTRY_USER: $(DOCKER_REGISTRY_USER)
          dockerRepo: tsystemsmms/phonebook-source-peoplesoft
          tag: $(Build.BuildId)
