trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - demo/source/
pr: none

jobs:
  - job: build
    displayName: build docker image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: |
          docker build -t $dockerRepo:$tag -f synthetic.Dockerfile .
          docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
          docker push $dockerRepo:$tag
        workingDirectory: 'demo/source/'
        env:
          DOCKER_REGISTRY_PASSWORD: $(DOCKER_REGISTRY_PASSWORD)
          DOCKER_REGISTRY_USER: $(DOCKER_REGISTRY_USER)
          dockerRepo: tsystemsmms/phonebook-build
          tag: mock-backend
