pr: 
  branches:
    include:
      - master

variables:
  image_repo: danielhabenicht/phonebook
  image_tag: pr-$(System.PullRequest.PullRequestNumber) 
  helm_artifact_name: HelmPhonebookPackage

jobs:
- job: build_phonebook_frontend
  displayName: 'Phonebook Frontend'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UseNode@1
    inputs:
      version: '11.x'

  - script: node version.js $(image_tag) $(Build.SourceVersion) $(Build.SourceVersion)
    displayName: 'Write Version Number'    
    workingDirectory: 'Phonebook.Frontend/'

  - script: docker build -t $(image_repo):$(image_tag) .
    displayName: 'Build Image'              
    workingDirectory: 'Phonebook.Frontend/'
  
  - script: |
      docker login -u $DOCKER_REGISTRY_USER -p $(DOCKER_REGISTRY_PASSWORD)
      docker push $(image_repo):$(image_tag)
    workingDirectory: 'Phonebook.Frontend/'
    displayName: 'Push Image'                      
    env:
      DOCKER_REGISTRY_PASSWORD: $(DOCKER_REGISTRY_PASSWORD)
      DOCKER_REGISTRY_USER: $(DOCKER_REGISTRY_USER)

- job: build_phonebook
  displayName: Phonebook
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: 'latest'
  - script: helm dep update
    workingDirectory: 'Phonebook/phonebook/'
  - task: HelmDeploy@0
    displayName: Helm package
    inputs:
      command: package
      chartPath: Phonebook/phonebook
      destination: $(Build.ArtifactStagingDirectory)
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: $(helm_artifact_name)
    
- job: deploy_preview
  dependsOn:
    - build_phonebook_frontend
    - build_phonebook
  displayName: 'Deploy Preview' 
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    namespace: $(image_tag)
    azure_public_ip_name: namespace_$(namespace)_public_ip
  steps:
  - download: current
    artifact: $(helm_artifact_name)

  - task: HelmInstaller@0
    displayName: 'Install Helm 2.14.2'
    inputs:
      helmVersion: 2.14.2
  
  - task: AzureCLI@1
    displayName: 'Azure CLI '
    inputs:
      azureSubscription: 'Visual Studio Enterprise – MPN (44678328-75c5-4e48-92c0-b2ab31d5166c)'
      scriptLocation: inlineScript
      inlineScript: |
        az network public-ip create \
            --resource-group MC_phonebook-kubernetes_phonebook-cluster_northeurope\
            --name $(azure_public_ip_name)\
            --allocation-method static

  - task: AzureCLI@1
    name: get_public_ip
    displayName: 'Azure CLI '
    inputs:
      azureSubscription: 'Visual Studio Enterprise – MPN (44678328-75c5-4e48-92c0-b2ab31d5166c)'
      scriptLocation: inlineScript
      inlineScript: |
        ip=`az network public-ip show --resource-group MC_phonebook-kubernetes_phonebook-cluster_northeurope --name $(azure_public_ip_name) --query ipAddress --output tsv`
        echo "##vso[task.setvariable variable=public_ip]$ip"
        echo "##vso[task.setvariable variable=public_ip;isOutput=true]$ip"

  - task: Kubernetes@1
    displayName: 'Create Namespace'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'Phonebook Kubernetes Demo Cluster'
      namespace: 'kube-public'
      command: 'apply'
      useConfigurationFile: true
      configurationType: 'inline'
      inline: |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: $(namespace)

  - task: HelmDeploy@0
    displayName: 'helm init'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'Phonebook Kubernetes Demo Cluster'
      namespace: $(namespace)
      command: init
      arguments: '--node-selectors "beta.kubernetes.io/os"="linux"'
      tillerNamespace: $(namespace)

  - task: HelmDeploy@0
    displayName: 'helm upgrade'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'Phonebook Kubernetes Demo Cluster'
      namespace: $(namespace)
      command: upgrade
      chartType: FilePath
      chartPath: '$(Pipeline.Workspace)/$(helm_artifact_name)/phonebook-0.1.0.tgz'
      releaseName: phonebook-$(namespace)
      overrideValues: 'frontend.image.tag=$(image_tag),frontend.image.repository=danielhabenicht,frontend.image.name=phonebook,traefik.kubernetes.namespaces={$(namespace)},traefik.loadBalancerIP=$(public_ip),host=$(public_ip)'
      valueFile: 'Phonebook.Demo/values.yml'
      recreate: true
      tillerNamespace: $(namespace)

  - task: Kubernetes@1
    displayName: 'kubectl create assets'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'Phonebook Kubernetes Demo Cluster'
      namespace: $(namespace)
      command: 'apply'
      useConfigurationFile: true
      configuration: 'Phonebook.Demo/Phonebook.Assets.yml'

  - task: Kubernetes@1
    displayName: 'kubectl create MockBackend'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'Phonebook Kubernetes Demo Cluster'
      namespace: $(namespace)
      command: 'apply'
      useConfigurationFile: true
      configuration: 'Phonebook.Demo/Phonebook.MockBackend.yml'

  - task: Kubernetes@1
    displayName: 'Delete Namespace'
    condition: failed()
    inputs:
      kubernetesServiceEndpoint: 'Phonebook Kubernetes Demo Cluster'
      namespace: 'kube-public'
      command: delete
      arguments: 'namespace $(namespace)'

  - task: Kubernetes@1
    displayName: 'Delete Clusterrole'
    condition: failed()
    inputs:
      kubernetesServiceEndpoint: 'Phonebook Kubernetes Demo Cluster'
      namespace: 'kube-public'
      command: delete
      arguments: 'clusterrole phonebook-$(image_tag)-traefik'

- job: notify
  displayName: 'Notify Github '
  pool: server
  dependsOn: deploy_preview
  variables: 
    public_ip: $[ dependencies.deploy_preview.outputs['get_public_ip.public_ip'] ]
  steps:
  - task: InvokeRESTAPI@1
    inputs:
      connectionType: 'connectedServiceName'
      serviceConnection: 'Github API Test'
      method: 'POST'
      headers: |
        {
        "Content-Type":"application/json"
        }
      body: |
        {
          "body": "Preview Environment ready at https://$(public_ip)"
        }
      urlSuffix: 'repos/T-Systems-MMS/phonebook/issues/$(System.PullRequest.PullRequestNumber)/comments'
      waitForCompletion: 'false'
