---
enabled: true
restylers:
  - prettier:
      include:
        - '**/*.js'
        - '**/*.ts'
        - '**/*.html'
        - '**/*.md'
        - '**/*.yml'
        - '**/*.yaml'
        - '**/*.json'
        - '**/*.css'
        - '**/*.scss'
