startupArguments:
  - ''
dashboard:
  enabled: true
  domain: board.demo-phonebook.me
ssl:
  enabled: true
  enforced: true
acme:
  staging: false
  enabled: true
  email: daniel-habenicht@outlook.de
  onHostRule: true
  challengeType: 'http-01'
  domains:
    enabled: true
    domainsList:
      - main: 'demo-phonebook.me'
      - sans:
          - 'board.demo-phonebook.me'
          - 'assets.demo-phonebook.me'
rbac:
  enabled: true
kubernetes:
  namespaces:
    - default
    - kube-system
