trigger: none
pr:
  branches:
    include:
      - master
  paths:
    include:
      - docs/**

jobs:
  - job: build
    displayName: build docs
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UseRubyVersion@0
        displayName: 'Use Ruby >= 2.5'

      - script: 'gem install bundler'
        displayName: 'Install Bundler'
        workingDirectory: 'docs/'

      - script: 'bundle install'
        displayName: 'Install Jekyll and Dependencies'
        workingDirectory: 'docs/'

      - script: 'bundle exec jekyll build'
        displayName: 'Build Jekyll Static Site'
        workingDirectory: 'docs/'
