trigger: none
pr:
  branches:
    include:
      - master
  paths:
    include:
      - /Phonebook/*

jobs:
  - job: helm
    displayName: helm 
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
     - script: helm dep update
       workingDirectory: /Phonebook/phonebook
     - script: helm package .\phonebook\
       workingDirectory: /Phonebook
    