trigger: none
pr:
  branches:
    include:
      - master
  paths:
    include:
      - Phonebook.Frontend/**

jobs:
  - job: E2E
    displayName: E2E Tests
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UseNode@1
        inputs:
          version: '11.x'

      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: 'Phonebook.Frontend/'

      - task: Npm@1
        displayName: 'run e2e tests'
        inputs:
          command: 'custom'
          workingDir: 'Phonebook.Frontend/'
          customCommand: 'run e2e'

  - job: Unit
    displayName: Unit Tests
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UseNode@1
        inputs:
          version: '11.x'

      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: 'Phonebook.Frontend/'

      - task: Npm@1
        displayName: 'run unit tests'
        inputs:
          command: 'custom'
          workingDir: 'Phonebook.Frontend/'
          customCommand: 'run test'

  - job: build
    displayName: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - task: UseNode@1
        inputs:
          version: '11.x'

      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: 'Phonebook.Frontend/'

      - task: Npm@1
        displayName: 'build app'
        inputs:
          command: 'custom'
          workingDir: 'Phonebook.Frontend/'
          customCommand: 'run build'
