trigger: none
pr:
  branches:
    include:
      - master
  paths:
    include:
      - Phonebook.Source.PeopleSoft/

jobs:
  - job: build
    displayName: build docker image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: |
          docker build .
        workingDirectory: 'Phonebook.Source.PeopleSoft/'
