trigger: none
pr:
  branches:
    include:
      - master
  paths:
    include:
      - demo/source/

jobs:
  - job: build
    displayName: build docker image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: |
          docker build -f synthetic.Dockerfile .
          docker build -f real.Dockerfile .
        workingDirectory: 'demo/source/'
