trigger: none
pr:
  branches:
    include:
      - master
  paths:
    include:
      - /Phonebook/*

jobs:
  - job: helm
    displayName: helm
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: HelmInstaller@1
        inputs:
          helmVersionToInstall: 'latest'
      - script: helm dep update
        workingDirectory: 'Phonebook/phonebook/'
      - task: HelmDeploy@0
        displayName: Helm package
        inputs:
          command: package
          chartPath: Phonebook/phonebook
          destination: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: drop
