trigger: none
pr:
  branches:
    include:
      - master
  paths:
    include:
      - demo/assets/**

jobs:
  - job: build
    displayName: build docker image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: |
          docker build .
        workingDirectory: 'demo/assets/'
