<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <NullableContextOptions>enable</NullableContextOptions>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="29.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.1.11" />
  </ItemGroup>

</Project>
