{{- if .Values.ingress.enabled -}}
{{- $fullName := include "phonebook.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-peoplesoft
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "phonebook.name" . }}-peoplesoft
    helm.sh/chart: {{ include "phonebook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  entryPoints:
    - web
    - websecure
  routes:                           
  - kind: Rule
    match: Host(`{{ .Values.host }}`) && PathPrefix(`/api`)
    priority: 50             
    middlewares:
    - name: ratelimit
      namespace: {{ .Release.Namespace }}
    services:                       
    - kind: Service
      name: {{ $fullName }}-peoplesoft
      namespace: {{ .Release.Namespace }}
      passHostHeader: true
      port: 80
      strategy: RoundRobin
      weight: 10
  tls:
    certResolver: default
    options:                        
      name: tlsoption
      namespace: {{ .Release.Namespace }}   
{{- end }}
