{{- if .Values.ingress.enabled -}}
{{- $fullName := include "phonebook.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-peoplesoft
  labels:
    app.kubernetes.io/name: {{ include "phonebook.name" . }}-peoplesoft
    helm.sh/chart: {{ include "phonebook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    traefik.ingress.kubernetes.io/router.priority: "50"
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /bla
            backend:
              serviceName: {{ $fullName }}-peoplesoft
              servicePort: http
{{- end }}
