apiVersion: v1
kind: Service
metadata:
  name: {{ include "phonebook.fullname" . }}-peoplesoft
  labels:
    app.kubernetes.io/name: {{ include "phonebook.name" . }}
    helm.sh/chart: {{ include "phonebook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.source.peoplesoft.service.type }}
  ports:
    - port: {{ .Values.source.peoplesoft.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "phonebook.name" . }}-peoplesoft
    app.kubernetes.io/instance: {{ .Release.Name }}
