version: '2.1'

services:
  ruby:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 4000:4000
    command: 'jekyll serve --host 0.0.0.0 --force-polling --baseurl /'
